// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUoK0xSVnRrDUC5j3GHM4fXb1DibFHs1o',
    appId: '1:919315527962:web:975dd67ea2702c9791d4a3',
    messagingSenderId: '919315527962',
    projectId: 'onboarding-screen-6c20f',
    authDomain: 'onboarding-screen-6c20f.firebaseapp.com',
    storageBucket: 'onboarding-screen-6c20f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwgn64Jc8w1LKwUzzi-6Q3VtqCWyeqPJU',
    appId: '1:919315527962:android:1aa053d76210221791d4a3',
    messagingSenderId: '919315527962',
    projectId: 'onboarding-screen-6c20f',
    storageBucket: 'onboarding-screen-6c20f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz3vn33f5avORL4fS_OXM5Cw0FaWTsT0A',
    appId: '1:919315527962:ios:39a2c5b797a9128291d4a3',
    messagingSenderId: '919315527962',
    projectId: 'onboarding-screen-6c20f',
    storageBucket: 'onboarding-screen-6c20f.firebasestorage.app',
    iosClientId: '919315527962-akkr6bcnku0ddlfve13rstc64l6p3lrt.apps.googleusercontent.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz3vn33f5avORL4fS_OXM5Cw0FaWTsT0A',
    appId: '1:919315527962:ios:39a2c5b797a9128291d4a3',
    messagingSenderId: '919315527962',
    projectId: 'onboarding-screen-6c20f',
    storageBucket: 'onboarding-screen-6c20f.firebasestorage.app',
    iosClientId: '919315527962-akkr6bcnku0ddlfve13rstc64l6p3lrt.apps.googleusercontent.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUoK0xSVnRrDUC5j3GHM4fXb1DibFHs1o',
    appId: '1:919315527962:web:177328771550c08e91d4a3',
    messagingSenderId: '919315527962',
    projectId: 'onboarding-screen-6c20f',
    authDomain: 'onboarding-screen-6c20f.firebaseapp.com',
    storageBucket: 'onboarding-screen-6c20f.firebasestorage.app',
  );
}
